# Application Configuration
app:
  name: "MySuperApp"
  version: "2.5.3"
  environment: "production"
  debug: false
  base_url: "https://api.mysuperapp.com"

# Database Configuration
database:
  type: "postgresql"
  host: "db.mysuperapp.com"
  port: 5432
  username: "app_user"
  password: "securepassword123"
  db_name: "mysuperapp_db"
  connection_pool_size: 15
  timeout: 30

# API Keys
api_keys:
  google_maps: "AIzaSyDpQJf9I-7JdhF9sjdfks9dfk9sd"
  stripe: "sk_test_4eC39HqLyjWDarjtT1zdp7dc"
  weather_service: "abc123xyz987"

# Features Flags
features:
  dark_mode: true
  notifications: true
  beta_access: false
  multi_language_support: true

# User Settings
user_settings:
  default_language: "en"
  time_zone: "America/New_York"
  preferred_currency: "USD"
  enable_tracking: false

# Logging Configuration
logging:
  level: "info"
  log_to_file: true
  log_file_path: "/var/log/mysuperapp.log"
  max_log_size_mb: 50
  retain_log_days: 7

# External Integrations
integrations:
  - name: "Slack"
    enabled: true
    webhook_url: "https://hooks.slack.com/services/xyz/abc/123"
  - name: "SendGrid"
    enabled: true
    api_key: "SG.xxxxxxx"
  - name: "GitHub"
    enabled: false
    api_url: "https://api.github.com"
  
# SMTP Configuration
smtp:
  server: "smtp.mysuperapp.com"
  port: 587
  username: "smtp_user"
  password: "smtp_password"
  encryption: "tls"
  from_email: "no-reply@mysuperapp.com"

# Email Templates
email_templates:
  welcome_email: "Welcome to MySuperApp! We're glad you're here."
  password_reset: "Click here to reset your password: {reset_link}"
  user_invite: "You've been invited to join MySuperApp. Here's your invitation link: {invite_link}"

# Payment Settings
payment:
  currency: "USD"
  tax_rate: 0.07
  enable_stripe: true
  enable_paypal: false
  stripe:
    webhook_secret: "whsec_12345abcdef"
  paypal:
    client_id: "ABC123PAYPAL"
    client_secret: "XYZ456PAYPAL"

# Security Settings
security:
  enable_2fa: true
  session_timeout_minutes: 30
  password_min_length: 8
  password_complexity: "upper, lower, digit, special_char"
  enable_account_lockout: true
  max_login_attempts: 5
  account_lockout_duration_minutes: 15

# Third-party Analytics
analytics:
  enabled: true
  service_name: "Mixpanel"
  api_key: "12345abcd67890efgh"
  event_tracking_enabled: true
  session_tracking_enabled: true
  page_view_tracking_enabled: true
